table_name: "kr_stock_dividend"
primary_key: ["ticker", "stac_yymm"]

# 1단계: 자동화된 데이터 클리닝 규칙
auto_cleaning_rules:
  replace_as_null: ["0", 0] # 결측치로 처리할 값 목록
  drop_nulls_threshold_count: 1000 # 이 개수 이상의 결측치를 가진 컬럼 제거
  drop_unique_threshold: 1 # 이 개수 이하의 고유값을 가진 컬럼 제거

# 2단계: 분석가가 직접 선정한 최종 사용 컬럼 목록
manual_column_selection:
  - ticker
  - record_date
  - divi_kind
  - per_sto_divi_amt
  - divi_rate
  - stk_divi_rate
  - divi_pay_dt

# 3단계: 자동 데이터 타입 변환 규칙
auto_dtype_rules:
  category_ratio: 0.05
  date_success_rate: 0.95

# 4단계: 수동 데이터 타입 변환 맵
manual_dtype_map:
  int64:
    - per_sto_divi_amt
  float64:
    - divi_rate
    - stk_divi_rate
  category:
    - ticker
    - divi_kind
  datetime64[ns]:
    - record_date
    - divi_pay_dt
