table_name: "kr_stock_basic_info"
primary_key: "ticker"

# 1단계: 자동화된 데이터 클리닝 규칙
auto_cleaning_rules:
  replace_as_null: ["0", 0] # 결측치로 처리할 값 목록
  drop_nulls_threshold: 50.0 # 이 개수 이상의 결측치를 가진 컬럼 제거
  drop_unique_threshold: 1 # 이 개수 이하의 고유값을 가진 컬럼 제거

# 2단계: 분석가가 직접 선정한 최종 사용 컬럼 목록
manual_column_selection:
  - ticker
  - lstg_stqt
  - cpta
  - papr
  - scts_mket_lstg_dt
  - frbd_mket_lstg_dt
  - idx_bztp_lcls_cd
  - idx_bztp_mcls_cd
  - idx_bztp_scls_cd
  - stck_kind_cd
  - prdt_name
  - prdt_abrv_name
  - std_pdno
  - sbst_pric
  - thdt_clpr
  - bfdy_clpr
  - std_idst_clsf_cd
  - std_idst_clsf_cd_name
  - idx_bztp_lcls_cd_name
  - idx_bztp_mcls_cd_name
  - idx_bztp_scls_cd_name
  - crfd_item_yn
  - issu_istt_cd
  - frnr_psnl_lmt_rt

# 3단계: 자동 데이터 타입 변환 규칙
auto_dtype_rules:
  category_ratio: 0.05
  date_success_rate: 0.95

# 4단계: 수동 데이터 타입 변환 맵
manual_dtype_map:
  int64:
    - lstg_stqt
    - cpta
    - papr
    - sbst_pric
  float64:
    - thdt_clpr
    - bfdy_clpr
    - frnr_psnl_lmt_rt
  category:
    - ticker
    - idx_bztp_mcls_cd
    - idx_bztp_scls_cd
    - std_pdno
    - std_idst_clsf_cd
    - std_idst_clsf_cd_name
    - idx_bztp_mcls_cd_name
    - idx_bztp_scls_cd_name
    - issu_istt_cd
  datetime64[ns]:
    - frbd_mket_lstg_dt
