# 최종 테이블 이름
final_table_name: "kr_stock_static_data"

source_tables:
  basic_info:
    table_name: "kr_stock_basic_info"
    columns:
      - "ticker"
      - "lstg_stqt"
      - "cpta"
      - "papr"
      - "scts_mket_lstg_dt"
      - "prdt_name"
      - "prdt_abrv_name"
      - "std_pdno"
      - "sbst_pric"
      - "thdt_clpr"
      - "bfdy_clpr"
      - "std_idst_clsf_cd_name"
      - "idx_bztp_lcls_cd_name"
      - "idx_bztp_scls_cd_name"
      - "issu_istt_cd"
  price_basic:
    table_name: "kr_stock_price_basic"
    columns:
      - "ticker"
      - "iscd_stat_cls_code"
      - "marg_rate"
      - "new_hgpr_lwpr_cls_code"
      - "bstp_kor_isnm"
      - "prdy_vrss"
      - "prdy_vrss_sign"
      - "prdy_ctrt"
      - "acml_tr_pbmn"
      - "acml_vol"
      - "prdy_vrss_vol_rate"
      - "stck_oprc"
      - "stck_hgpr"
      - "stck_lwpr"
      - "stck_mxpr"
      - "stck_llam"
      - "stck_sdpr"
      - "wghn_avrg_stck_prc"
      - "hts_frgn_ehrt"
      - "frgn_ntby_qty"
      - "pgtr_ntby_qty"
      - "pvt_scnd_dmrs_prc"
      - "pvt_frst_dmrs_prc"
      - "pvt_pont_val"
      - "pvt_frst_dmsp_prc"
      - "pvt_scnd_dmsp_prc"
      - "dmrs_val"
      - "dmsp_val"
      - "stck_sspr"
      - "aspr_unit"
      - "hts_avls"
      - "per"
      - "pbr"
      - "vol_tnrt"
      - "eps"
      - "bps"
      - "d250_hgpr"
      - "d250_hgpr_date"
      - "d250_hgpr_vrss_prpr_rate"
      - "d250_lwpr"
      - "d250_lwpr_date"
      - "d250_lwpr_vrss_prpr_rate"
      - "stck_dryy_hgpr"
      - "dryy_hgpr_vrss_prpr_rate"
      - "dryy_hgpr_date"
      - "stck_dryy_lwpr"
      - "dryy_lwpr_vrss_prpr_rate"
      - "dryy_lwpr_date"
      - "w52_hgpr"
      - "w52_hgpr_vrss_prpr_ctrt"
      - "w52_hgpr_date"
      - "w52_lwpr"
      - "w52_lwpr_vrss_prpr_ctrt"
      - "w52_lwpr_date"
      - "whol_loan_rmnd_rate"
      - "stck_shrn_iscd"
      - "cpfn_cnnm"
      - "frgn_hldn_qty"
      - "last_ssts_cntg_qty"
  asking_price:
    table_name: "kr_stock_asking_price"
    columns:
      - "ticker"
      - "aspr_acpt_hour"
      - "askp1"
      - "askp10"
      - "bidp1"
      - "bidp10"
      - "askp_rsqn1"
      - "askp_rsqn2"
      - "askp_rsqn3"
      - "askp_rsqn4"
      - "askp_rsqn5"
      - "askp_rsqn6"
      - "askp_rsqn7"
      - "askp_rsqn8"
      - "askp_rsqn9"
      - "askp_rsqn10"
      - "bidp_rsqn1"
      - "bidp_rsqn2"
      - "bidp_rsqn3"
      - "bidp_rsqn4"
      - "bidp_rsqn5"
      - "bidp_rsqn6"
      - "bidp_rsqn7"
      - "bidp_rsqn8"
      - "bidp_rsqn9"
      - "bidp_rsqn10"
      - "total_askp_rsqn"
      - "total_bidp_rsqn"
      - "ntby_aspr_rsqn"
      - "new_mkop_cls_code"
  price_detail:
    table_name: "kr_stock_price_detail"
    columns:
      - "ticker"
      - "prdy_clpr_vrss_oprc_rate"
      - "lwpr_vrss_prpr"
      - "lwpr_vrss_prpr_sign"
      - "prdy_clpr_vrss_lwpr_rate"
      - "hgpr_vrss_prpr"
      - "hgpr_vrss_prpr_sign"
      - "prdy_clpr_vrss_hgpr_rate"
      - "oprc_vrss_prpr"
      - "oprc_vrss_prpr_sign"
      - "bstp_cls_code"
      - "prdy_vol"

merge_strategy:
  base_table: "basic_info"
  merge_sequence:
    - "price_basic"
    - "asking_price"
    - "price_detail"
  join_key: "ticker"
  join_how: "left"
