-- kr_stock_basic_info 테이블에 데이터를 삽입하거나, 
-- ticker이 동일한 데이터가 이미 존재하는 경우 최신 정보로 업데이트합니다. (UPSERT)
INSERT INTO kr_stock_basic_info (
  ticker, 
  pdno, prdt_type_cd, mket_id_cd, scty_grp_id_cd, excg_dvsn_cd, setl_mmdd, 
  lstg_stqt, lstg_cptl_amt, cpta, papr, issu_pric, kospi200_item_yn, 
  scts_mket_lstg_dt, scts_mket_lstg_abol_dt, kosdaq_mket_lstg_dt, 
  kosdaq_mket_lstg_abol_dt, frbd_mket_lstg_dt, frbd_mket_lstg_abol_dt, 
  reits_kind_cd, etf_dvsn_cd, oilf_fund_yn, idx_bztp_lcls_cd, 
  idx_bztp_mcls_cd, idx_bztp_scls_cd, stck_kind_cd, mfnd_opng_dt, 
  mfnd_end_dt, dpsi_erlm_cncl_dt, etf_cu_qty, prdt_name, prdt_name120, 
  prdt_abrv_name, std_pdno, prdt_eng_name, prdt_eng_name120, 
  prdt_eng_abrv_name, dpsi_aptm_erlm_yn, etf_txtn_type_cd, etf_type_cd, 
  lstg_abol_dt, nwst_odst_dvsn_cd, sbst_pric, thco_sbst_pric, 
  thco_sbst_pric_chng_dt, tr_stop_yn, admn_item_yn, thdt_clpr, bfdy_clpr, 
  clpr_chng_dt, std_idst_clsf_cd, std_idst_clsf_cd_name, 
  idx_bztp_lcls_cd_name, idx_bztp_mcls_cd_name, idx_bztp_scls_cd_name, 
  ocr_no, crfd_item_yn, elec_scty_yn, issu_istt_cd, etf_chas_erng_rt_dbnb, 
  etf_etn_ivst_heed_item_yn, stln_int_rt_dvsn_cd, frnr_psnl_lmt_rt, 
  lstg_rqsr_issu_istt_cd, lstg_rqsr_item_cd, trst_istt_issu_istt_cd, 
  cptt_trad_tr_psbl_yn, nxt_tr_stop_yn
) VALUES (
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 
  %s, %s, %s, %s
)
ON CONFLICT (ticker) DO UPDATE SET
  pdno = EXCLUDED.pdno,
  prdt_type_cd = EXCLUDED.prdt_type_cd,
  mket_id_cd = EXCLUDED.mket_id_cd,
  scty_grp_id_cd = EXCLUDED.scty_grp_id_cd,
  excg_dvsn_cd = EXCLUDED.excg_dvsn_cd,
  setl_mmdd = EXCLUDED.setl_mmdd,
  lstg_stqt = EXCLUDED.lstg_stqt,
  lstg_cptl_amt = EXCLUDED.lstg_cptl_amt,
  cpta = EXCLUDED.cpta,
  papr = EXCLUDED.papr,
  issu_pric = EXCLUDED.issu_pric,
  kospi200_item_yn = EXCLUDED.kospi200_item_yn,
  scts_mket_lstg_dt = EXCLUDED.scts_mket_lstg_dt,
  scts_mket_lstg_abol_dt = EXCLUDED.scts_mket_lstg_abol_dt,
  kosdaq_mket_lstg_dt = EXCLUDED.kosdaq_mket_lstg_dt,
  kosdaq_mket_lstg_abol_dt = EXCLUDED.kosdaq_mket_lstg_abol_dt,
  frbd_mket_lstg_dt = EXCLUDED.frbd_mket_lstg_dt,
  frbd_mket_lstg_abol_dt = EXCLUDED.frbd_mket_lstg_abol_dt,
  reits_kind_cd = EXCLUDED.reits_kind_cd,
  etf_dvsn_cd = EXCLUDED.etf_dvsn_cd,
  oilf_fund_yn = EXCLUDED.oilf_fund_yn,
  idx_bztp_lcls_cd = EXCLUDED.idx_bztp_lcls_cd,
  idx_bztp_mcls_cd = EXCLUDED.idx_bztp_mcls_cd,
  idx_bztp_scls_cd = EXCLUDED.idx_bztp_scls_cd,
  stck_kind_cd = EXCLUDED.stck_kind_cd,
  mfnd_opng_dt = EXCLUDED.mfnd_opng_dt,
  mfnd_end_dt = EXCLUDED.mfnd_end_dt,
  dpsi_erlm_cncl_dt = EXCLUDED.dpsi_erlm_cncl_dt,
  etf_cu_qty = EXCLUDED.etf_cu_qty,
  prdt_name = EXCLUDED.prdt_name,
  prdt_name120 = EXCLUDED.prdt_name120,
  prdt_abrv_name = EXCLUDED.prdt_abrv_name,
  std_pdno = EXCLUDED.std_pdno,
  prdt_eng_name = EXCLUDED.prdt_eng_name,
  prdt_eng_name120 = EXCLUDED.prdt_eng_name120,
  prdt_eng_abrv_name = EXCLUDED.prdt_eng_abrv_name,
  dpsi_aptm_erlm_yn = EXCLUDED.dpsi_aptm_erlm_yn,
  etf_txtn_type_cd = EXCLUDED.etf_txtn_type_cd,
  etf_type_cd = EXCLUDED.etf_type_cd,
  lstg_abol_dt = EXCLUDED.lstg_abol_dt,
  nwst_odst_dvsn_cd = EXCLUDED.nwst_odst_dvsn_cd,
  sbst_pric = EXCLUDED.sbst_pric,
  thco_sbst_pric = EXCLUDED.thco_sbst_pric,
  thco_sbst_pric_chng_dt = EXCLUDED.thco_sbst_pric_chng_dt,
  tr_stop_yn = EXCLUDED.tr_stop_yn,
  admn_item_yn = EXCLUDED.admn_item_yn,
  thdt_clpr = EXCLUDED.thdt_clpr,
  bfdy_clpr = EXCLUDED.bfdy_clpr,
  clpr_chng_dt = EXCLUDED.clpr_chng_dt,
  std_idst_clsf_cd = EXCLUDED.std_idst_clsf_cd,
  std_idst_clsf_cd_name = EXCLUDED.std_idst_clsf_cd_name,
  idx_bztp_lcls_cd_name = EXCLUDED.idx_bztp_lcls_cd_name,
  idx_bztp_mcls_cd_name = EXCLUDED.idx_bztp_mcls_cd_name,
  idx_bztp_scls_cd_name = EXCLUDED.idx_bztp_scls_cd_name,
  ocr_no = EXCLUDED.ocr_no,
  crfd_item_yn = EXCLUDED.crfd_item_yn,
  elec_scty_yn = EXCLUDED.elec_scty_yn,
  issu_istt_cd = EXCLUDED.issu_istt_cd,
  etf_chas_erng_rt_dbnb = EXCLUDED.etf_chas_erng_rt_dbnb,
  etf_etn_ivst_heed_item_yn = EXCLUDED.etf_etn_ivst_heed_item_yn,
  stln_int_rt_dvsn_cd = EXCLUDED.stln_int_rt_dvsn_cd,
  frnr_psnl_lmt_rt = EXCLUDED.frnr_psnl_lmt_rt,
  lstg_rqsr_issu_istt_cd = EXCLUDED.lstg_rqsr_issu_istt_cd,
  lstg_rqsr_item_cd = EXCLUDED.lstg_rqsr_item_cd,
  trst_istt_issu_istt_cd = EXCLUDED.trst_istt_issu_istt_cd,
  cptt_trad_tr_psbl_yn = EXCLUDED.cptt_trad_tr_psbl_yn,
  nxt_tr_stop_yn = EXCLUDED.nxt_tr_stop_yn,
  updated_at = CURRENT_TIMESTAMP;