-- kr_stock_member 테이블에 데이터를 삽입하거나,
-- ticker가 동일한 데이터가 이미 존재하는 경우 최신 정보로 업데이트합니다. (UPSERT)

INSERT INTO kr_stock_member (
  ticker, seln_mbcr_no1, seln_mbcr_no2, seln_mbcr_no3, seln_mbcr_no4, seln_mbcr_no5, seln_mbcr_name1,
  seln_mbcr_name2, seln_mbcr_name3, seln_mbcr_name4, seln_mbcr_name5, total_seln_qty1, total_seln_qty2,
  total_seln_qty3, total_seln_qty4, total_seln_qty5, seln_mbcr_rlim1, seln_mbcr_rlim2, seln_mbcr_rlim3,
  seln_mbcr_rlim4, seln_mbcr_rlim5, seln_qty_icdc1, seln_qty_icdc2, seln_qty_icdc3, seln_qty_icdc4,
  seln_qty_icdc5, shnu_mbcr_no1, shnu_mbcr_no2, shnu_mbcr_no3, shnu_mbcr_no4, shnu_mbcr_no5,
  shnu_mbcr_name1, shnu_mbcr_name2, shnu_mbcr_name3, shnu_mbcr_name4, shnu_mbcr_name5, total_shnu_qty1,
  total_shnu_qty2, total_shnu_qty3, total_shnu_qty4, total_shnu_qty5, shnu_mbcr_rlim1, shnu_mbcr_rlim2,
  shnu_mbcr_rlim3, shnu_mbcr_rlim4, shnu_mbcr_rlim5, shnu_qty_icdc1, shnu_qty_icdc2, shnu_qty_icdc3,
  shnu_qty_icdc4, shnu_qty_icdc5, glob_total_seln_qty, glob_seln_rlim, glob_ntby_qty,
  glob_total_shnu_qty, glob_shnu_rlim, seln_mbcr_glob_yn_1, seln_mbcr_glob_yn_2, seln_mbcr_glob_yn_3,
  seln_mbcr_glob_yn_4, seln_mbcr_glob_yn_5, shnu_mbcr_glob_yn_1, shnu_mbcr_glob_yn_2,
  shnu_mbcr_glob_yn_3, shnu_mbcr_glob_yn_4, shnu_mbcr_glob_yn_5, glob_total_seln_qty_icdc,
  glob_total_shnu_qty_icdc
) VALUES (
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
  %s, %s, %s, %s, %s, %s, %s, %s
)
ON CONFLICT (ticker) DO UPDATE SET
  seln_mbcr_no1 = EXCLUDED.seln_mbcr_no1,
  seln_mbcr_no2 = EXCLUDED.seln_mbcr_no2,
  seln_mbcr_no3 = EXCLUDED.seln_mbcr_no3,
  seln_mbcr_no4 = EXCLUDED.seln_mbcr_no4,
  seln_mbcr_no5 = EXCLUDED.seln_mbcr_no5,
  seln_mbcr_name1 = EXCLUDED.seln_mbcr_name1,
  seln_mbcr_name2 = EXCLUDED.seln_mbcr_name2,
  seln_mbcr_name3 = EXCLUDED.seln_mbcr_name3,
  seln_mbcr_name4 = EXCLUDED.seln_mbcr_name4,
  seln_mbcr_name5 = EXCLUDED.seln_mbcr_name5,
  total_seln_qty1 = EXCLUDED.total_seln_qty1,
  total_seln_qty2 = EXCLUDED.total_seln_qty2,
  total_seln_qty3 = EXCLUDED.total_seln_qty3,
  total_seln_qty4 = EXCLUDED.total_seln_qty4,
  total_seln_qty5 = EXCLUDED.total_seln_qty5,
  seln_mbcr_rlim1 = EXCLUDED.seln_mbcr_rlim1,
  seln_mbcr_rlim2 = EXCLUDED.seln_mbcr_rlim2,
  seln_mbcr_rlim3 = EXCLUDED.seln_mbcr_rlim3,
  seln_mbcr_rlim4 = EXCLUDED.seln_mbcr_rlim4,
  seln_mbcr_rlim5 = EXCLUDED.seln_mbcr_rlim5,
  seln_qty_icdc1 = EXCLUDED.seln_qty_icdc1,
  seln_qty_icdc2 = EXCLUDED.seln_qty_icdc2,
  seln_qty_icdc3 = EXCLUDED.seln_qty_icdc3,
  seln_qty_icdc4 = EXCLUDED.seln_qty_icdc4,
  seln_qty_icdc5 = EXCLUDED.seln_qty_icdc5,
  shnu_mbcr_no1 = EXCLUDED.shnu_mbcr_no1,
  shnu_mbcr_no2 = EXCLUDED.shnu_mbcr_no2,
  shnu_mbcr_no3 = EXCLUDED.shnu_mbcr_no3,
  shnu_mbcr_no4 = EXCLUDED.shnu_mbcr_no4,
  shnu_mbcr_no5 = EXCLUDED.shnu_mbcr_no5,
  shnu_mbcr_name1 = EXCLUDED.shnu_mbcr_name1,
  shnu_mbcr_name2 = EXCLUDED.shnu_mbcr_name2,
  shnu_mbcr_name3 = EXCLUDED.shnu_mbcr_name3,
  shnu_mbcr_name4 = EXCLUDED.shnu_mbcr_name4,
  shnu_mbcr_name5 = EXCLUDED.shnu_mbcr_name5,
  total_shnu_qty1 = EXCLUDED.total_shnu_qty1,
  total_shnu_qty2 = EXCLUDED.total_shnu_qty2,
  total_shnu_qty3 = EXCLUDED.total_shnu_qty3,
  total_shnu_qty4 = EXCLUDED.total_shnu_qty4,
  total_shnu_qty5 = EXCLUDED.total_shnu_qty5,
  shnu_mbcr_rlim1 = EXCLUDED.shnu_mbcr_rlim1,
  shnu_mbcr_rlim2 = EXCLUDED.shnu_mbcr_rlim2,
  shnu_mbcr_rlim3 = EXCLUDED.shnu_mbcr_rlim3,
  shnu_mbcr_rlim4 = EXCLUDED.shnu_mbcr_rlim4,
  shnu_mbcr_rlim5 = EXCLUDED.shnu_mbcr_rlim5,
  shnu_qty_icdc1 = EXCLUDED.shnu_qty_icdc1,
  shnu_qty_icdc2 = EXCLUDED.shnu_qty_icdc2,
  shnu_qty_icdc3 = EXCLUDED.shnu_qty_icdc3,
  shnu_qty_icdc4 = EXCLUDED.shnu_qty_icdc4,
  shnu_qty_icdc5 = EXCLUDED.shnu_qty_icdc5,
  glob_total_seln_qty = EXCLUDED.glob_total_seln_qty,
  glob_seln_rlim = EXCLUDED.glob_seln_rlim,
  glob_ntby_qty = EXCLUDED.glob_ntby_qty,
  glob_total_shnu_qty = EXCLUDED.glob_total_shnu_qty,
  glob_shnu_rlim = EXCLUDED.glob_shnu_rlim,
  seln_mbcr_glob_yn_1 = EXCLUDED.seln_mbcr_glob_yn_1,
  seln_mbcr_glob_yn_2 = EXCLUDED.seln_mbcr_glob_yn_2,
  seln_mbcr_glob_yn_3 = EXCLUDED.seln_mbcr_glob_yn_3,
  seln_mbcr_glob_yn_4 = EXCLUDED.seln_mbcr_glob_yn_4,
  seln_mbcr_glob_yn_5 = EXCLUDED.seln_mbcr_glob_yn_5,
  shnu_mbcr_glob_yn_1 = EXCLUDED.shnu_mbcr_glob_yn_1,
  shnu_mbcr_glob_yn_2 = EXCLUDED.shnu_mbcr_glob_yn_2,
  shnu_mbcr_glob_yn_3 = EXCLUDED.shnu_mbcr_glob_yn_3,
  shnu_mbcr_glob_yn_4 = EXCLUDED.shnu_mbcr_glob_yn_4,
  shnu_mbcr_glob_yn_5 = EXCLUDED.shnu_mbcr_glob_yn_5,
  glob_total_seln_qty_icdc = EXCLUDED.glob_total_seln_qty_icdc,
  glob_total_shnu_qty_icdc = EXCLUDED.glob_total_shnu_qty_icdc,
  updated_at = CURRENT_TIMESTAMP;