-- kr_stock_price_basic 테이블에 데이터를 삽입하거나,
-- ticker가 동일한 데이터가 이미 존재하는 경우 최신 정보로 업데이트합니다. (UPSERT)

INSERT INTO kr_stock_price_basic (
  ticker, iscd_stat_cls_code, marg_rate, rprs_mrkt_kor_name, new_hgpr_lwpr_cls_code, bstp_kor_isnm,
  temp_stop_yn, oprc_rang_cont_yn, clpr_rang_cont_yn, crdt_able_yn, grmn_rate_cls_code, elw_pblc_yn,
  stck_prpr, prdy_vrss, prdy_vrss_sign, prdy_ctrt, acml_tr_pbmn, acml_vol, prdy_vrss_vol_rate, stck_oprc,
  stck_hgpr, stck_lwpr, stck_mxpr, stck_llam, stck_sdpr, wghn_avrg_stck_prc, hts_frgn_ehrt, frgn_ntby_qty,
  pgtr_ntby_qty, pvt_scnd_dmrs_prc, pvt_frst_dmrs_prc, pvt_pont_val, pvt_frst_dmsp_prc,
  pvt_scnd_dmsp_prc, dmrs_val, dmsp_val, cpfn, rstc_wdth_prc, stck_fcam, stck_sspr, aspr_unit,
  hts_deal_qty_unit_val, lstn_stcn, hts_avls, per, pbr, stac_month, vol_tnrt, eps, bps, d250_hgpr,
  d250_hgpr_date, d250_hgpr_vrss_prpr_rate, d250_lwpr, d250_lwpr_date, d250_lwpr_vrss_prpr_rate,
  stck_dryy_hgpr, dryy_hgpr_vrss_prpr_rate, dryy_hgpr_date, stck_dryy_lwpr, dryy_lwpr_vrss_prpr_rate,
  dryy_lwpr_date, w52_hgpr, w52_hgpr_vrss_prpr_ctrt, w52_hgpr_date, w52_lwpr, w52_lwpr_vrss_prpr_ctrt,
  w52_lwpr_date, whol_loan_rmnd_rate, ssts_yn, stck_shrn_iscd, fcam_cnnm, cpfn_cnnm, apprch_rate,
  frgn_hldn_qty, vi_cls_code, ovtm_vi_cls_code, last_ssts_cntg_qty, invt_caful_yn, mrkt_warn_cls_code,
  short_over_yn, sltr_yn, mang_issu_cls_code
) VALUES (
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
  %s, %s, %s
)
ON CONFLICT (ticker) DO UPDATE SET
  iscd_stat_cls_code = EXCLUDED.iscd_stat_cls_code,
  marg_rate = EXCLUDED.marg_rate,
  rprs_mrkt_kor_name = EXCLUDED.rprs_mrkt_kor_name,
  new_hgpr_lwpr_cls_code = EXCLUDED.new_hgpr_lwpr_cls_code,
  bstp_kor_isnm = EXCLUDED.bstp_kor_isnm,
  temp_stop_yn = EXCLUDED.temp_stop_yn,
  oprc_rang_cont_yn = EXCLUDED.oprc_rang_cont_yn,
  clpr_rang_cont_yn = EXCLUDED.clpr_rang_cont_yn,
  crdt_able_yn = EXCLUDED.crdt_able_yn,
  grmn_rate_cls_code = EXCLUDED.grmn_rate_cls_code,
  elw_pblc_yn = EXCLUDED.elw_pblc_yn,
  stck_prpr = EXCLUDED.stck_prpr,
  prdy_vrss = EXCLUDED.prdy_vrss,
  prdy_vrss_sign = EXCLUDED.prdy_vrss_sign,
  prdy_ctrt = EXCLUDED.prdy_ctrt,
  acml_tr_pbmn = EXCLUDED.acml_tr_pbmn,
  acml_vol = EXCLUDED.acml_vol,
  prdy_vrss_vol_rate = EXCLUDED.prdy_vrss_vol_rate,
  stck_oprc = EXCLUDED.stck_oprc,
  stck_hgpr = EXCLUDED.stck_hgpr,
  stck_lwpr = EXCLUDED.stck_lwpr,
  stck_mxpr = EXCLUDED.stck_mxpr,
  stck_llam = EXCLUDED.stck_llam,
  stck_sdpr = EXCLUDED.stck_sdpr,
  wghn_avrg_stck_prc = EXCLUDED.wghn_avrg_stck_prc,
  hts_frgn_ehrt = EXCLUDED.hts_frgn_ehrt,
  frgn_ntby_qty = EXCLUDED.frgn_ntby_qty,
  pgtr_ntby_qty = EXCLUDED.pgtr_ntby_qty,
  pvt_scnd_dmrs_prc = EXCLUDED.pvt_scnd_dmrs_prc,
  pvt_frst_dmrs_prc = EXCLUDED.pvt_frst_dmrs_prc,
  pvt_pont_val = EXCLUDED.pvt_pont_val,
  pvt_frst_dmsp_prc = EXCLUDED.pvt_frst_dmsp_prc,
  pvt_scnd_dmsp_prc = EXCLUDED.pvt_scnd_dmsp_prc,
  dmrs_val = EXCLUDED.dmrs_val,
  dmsp_val = EXCLUDED.dmsp_val,
  cpfn = EXCLUDED.cpfn,
  rstc_wdth_prc = EXCLUDED.rstc_wdth_prc,
  stck_fcam = EXCLUDED.stck_fcam,
  stck_sspr = EXCLUDED.stck_sspr,
  aspr_unit = EXCLUDED.aspr_unit,
  hts_deal_qty_unit_val = EXCLUDED.hts_deal_qty_unit_val,
  lstn_stcn = EXCLUDED.lstn_stcn,
  hts_avls = EXCLUDED.hts_avls,
  per = EXCLUDED.per,
  pbr = EXCLUDED.pbr,
  stac_month = EXCLUDED.stac_month,
  vol_tnrt = EXCLUDED.vol_tnrt,
  eps = EXCLUDED.eps,
  bps = EXCLUDED.bps,
  d250_hgpr = EXCLUDED.d250_hgpr,
  d250_hgpr_date = EXCLUDED.d250_hgpr_date,
  d250_hgpr_vrss_prpr_rate = EXCLUDED.d250_hgpr_vrss_prpr_rate,
  d250_lwpr = EXCLUDED.d250_lwpr,
  d250_lwpr_date = EXCLUDED.d250_lwpr_date,
  d250_lwpr_vrss_prpr_rate = EXCLUDED.d250_lwpr_vrss_prpr_rate,
  stck_dryy_hgpr = EXCLUDED.stck_dryy_hgpr,
  dryy_hgpr_vrss_prpr_rate = EXCLUDED.dryy_hgpr_vrss_prpr_rate,
  dryy_hgpr_date = EXCLUDED.dryy_hgpr_date,
  stck_dryy_lwpr = EXCLUDED.stck_dryy_lwpr,
  dryy_lwpr_vrss_prpr_rate = EXCLUDED.dryy_lwpr_vrss_prpr_rate,
  dryy_lwpr_date = EXCLUDED.dryy_lwpr_date,
  w52_hgpr = EXCLUDED.w52_hgpr,
  w52_hgpr_vrss_prpr_ctrt = EXCLUDED.w52_hgpr_vrss_prpr_ctrt,
  w52_hgpr_date = EXCLUDED.w52_hgpr_date,
  w52_lwpr = EXCLUDED.w52_lwpr,
  w52_lwpr_vrss_prpr_ctrt = EXCLUDED.w52_lwpr_vrss_prpr_ctrt,
  w52_lwpr_date = EXCLUDED.w52_lwpr_date,
  whol_loan_rmnd_rate = EXCLUDED.whol_loan_rmnd_rate,
  ssts_yn = EXCLUDED.ssts_yn,
  stck_shrn_iscd = EXCLUDED.stck_shrn_iscd,
  fcam_cnnm = EXCLUDED.fcam_cnnm,
  cpfn_cnnm = EXCLUDED.cpfn_cnnm,
  apprch_rate = EXCLUDED.apprch_rate,
  frgn_hldn_qty = EXCLUDED.frgn_hldn_qty,
  vi_cls_code = EXCLUDED.vi_cls_code,
  ovtm_vi_cls_code = EXCLUDED.ovtm_vi_cls_code,
  last_ssts_cntg_qty = EXCLUDED.last_ssts_cntg_qty,
  invt_caful_yn = EXCLUDED.invt_caful_yn,
  mrkt_warn_cls_code = EXCLUDED.mrkt_warn_cls_code,
  short_over_yn = EXCLUDED.short_over_yn,
  sltr_yn = EXCLUDED.sltr_yn,
  mang_issu_cls_code = EXCLUDED.mang_issu_cls_code,
  updated_at = CURRENT_TIMESTAMP;