-- kr_stock_price_detail 테이블에 데이터를 삽입하거나,
-- ticker가 동일한 데이터가 이미 존재하는 경우 최신 정보로 업데이트합니다. (UPSERT)

INSERT INTO kr_stock_price_detail (
  ticker, rprs_mrkt_kor_name, new_hgpr_lwpr_cls_code, mxpr_llam_cls_code, crdt_able_yn, stck_mxpr, 
  elw_pblc_yn, prdy_clpr_vrss_oprc_rate, crdt_rate, marg_rate, lwpr_vrss_prpr, lwpr_vrss_prpr_sign, 
  prdy_clpr_vrss_lwpr_rate, stck_lwpr, hgpr_vrss_prpr, hgpr_vrss_prpr_sign, prdy_clpr_vrss_hgpr_rate, 
  stck_hgpr, oprc_vrss_prpr, oprc_vrss_prpr_sign, mang_issu_yn, divi_app_cls_code, short_over_yn, 
  mrkt_warn_cls_code, invt_caful_yn, stange_runup_yn, ssts_hot_yn, low_current_yn, vi_cls_code, 
  short_over_cls_code, stck_llam, new_lstn_cls_name, vlnt_deal_cls_name, flng_cls_name, 
  revl_issu_reas_name, mrkt_warn_cls_name, stck_sdpr, bstp_cls_code, stck_prdy_clpr, insn_pbnt_yn, 
  fcam_mod_cls_name, stck_prpr, prdy_vrss, prdy_vrss_sign, prdy_ctrt, acml_tr_pbmn, acml_vol, 
  prdy_vrss_vol_rate, bstp_kor_isnm, sltr_yn, trht_yn, oprc_rang_cont_yn, vlnt_fin_cls_code, 
  stck_oprc, prdy_vol
) VALUES (
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
)
ON CONFLICT (ticker) DO UPDATE SET
  rprs_mrkt_kor_name = EXCLUDED.rprs_mrkt_kor_name,
  new_hgpr_lwpr_cls_code = EXCLUDED.new_hgpr_lwpr_cls_code,
  mxpr_llam_cls_code = EXCLUDED.mxpr_llam_cls_code,
  crdt_able_yn = EXCLUDED.crdt_able_yn,
  stck_mxpr = EXCLUDED.stck_mxpr,
  elw_pblc_yn = EXCLUDED.elw_pblc_yn,
  prdy_clpr_vrss_oprc_rate = EXCLUDED.prdy_clpr_vrss_oprc_rate,
  crdt_rate = EXCLUDED.crdt_rate,
  marg_rate = EXCLUDED.marg_rate,
  lwpr_vrss_prpr = EXCLUDED.lwpr_vrss_prpr,
  lwpr_vrss_prpr_sign = EXCLUDED.lwpr_vrss_prpr_sign,
  prdy_clpr_vrss_lwpr_rate = EXCLUDED.prdy_clpr_vrss_lwpr_rate,
  stck_lwpr = EXCLUDED.stck_lwpr,
  hgpr_vrss_prpr = EXCLUDED.hgpr_vrss_prpr,
  hgpr_vrss_prpr_sign = EXCLUDED.hgpr_vrss_prpr_sign,
  prdy_clpr_vrss_hgpr_rate = EXCLUDED.prdy_clpr_vrss_hgpr_rate,
  stck_hgpr = EXCLUDED.stck_hgpr,
  oprc_vrss_prpr = EXCLUDED.oprc_vrss_prpr,
  oprc_vrss_prpr_sign = EXCLUDED.oprc_vrss_prpr_sign,
  mang_issu_yn = EXCLUDED.mang_issu_yn,
  divi_app_cls_code = EXCLUDED.divi_app_cls_code,
  short_over_yn = EXCLUDED.short_over_yn,
  mrkt_warn_cls_code = EXCLUDED.mrkt_warn_cls_code,
  invt_caful_yn = EXCLUDED.invt_caful_yn,
  stange_runup_yn = EXCLUDED.stange_runup_yn,
  ssts_hot_yn = EXCLUDED.ssts_hot_yn,
  low_current_yn = EXCLUDED.low_current_yn,
  vi_cls_code = EXCLUDED.vi_cls_code,
  short_over_cls_code = EXCLUDED.short_over_cls_code,
  stck_llam = EXCLUDED.stck_llam,
  new_lstn_cls_name = EXCLUDED.new_lstn_cls_name,
  vlnt_deal_cls_name = EXCLUDED.vlnt_deal_cls_name,
  flng_cls_name = EXCLUDED.flng_cls_name,
  revl_issu_reas_name = EXCLUDED.revl_issu_reas_name,
  mrkt_warn_cls_name = EXCLUDED.mrkt_warn_cls_name,
  stck_sdpr = EXCLUDED.stck_sdpr,
  bstp_cls_code = EXCLUDED.bstp_cls_code,
  stck_prdy_clpr = EXCLUDED.stck_prdy_clpr,
  insn_pbnt_yn = EXCLUDED.insn_pbnt_yn,
  fcam_mod_cls_name = EXCLUDED.fcam_mod_cls_name,
  stck_prpr = EXCLUDED.stck_prpr,
  prdy_vrss = EXCLUDED.prdy_vrss,
  prdy_vrss_sign = EXCLUDED.prdy_vrss_sign,
  prdy_ctrt = EXCLUDED.prdy_ctrt,
  acml_tr_pbmn = EXCLUDED.acml_tr_pbmn,
  acml_vol = EXCLUDED.acml_vol,
  prdy_vrss_vol_rate = EXCLUDED.prdy_vrss_vol_rate,
  bstp_kor_isnm = EXCLUDED.bstp_kor_isnm,
  sltr_yn = EXCLUDED.sltr_yn,
  trht_yn = EXCLUDED.trht_yn,
  oprc_rang_cont_yn = EXCLUDED.oprc_rang_cont_yn,
  vlnt_fin_cls_code = EXCLUDED.vlnt_fin_cls_code,
  stck_oprc = EXCLUDED.stck_oprc,
  prdy_vol = EXCLUDED.prdy_vol,
  updated_at = CURRENT_TIMESTAMP;