-- kr_stock_asking_price 테이블에 데이터를 삽입하거나,
-- ticker가 동일한 데이터가 이미 존재하는 경우 최신 정보로 업데이트합니다. (UPSERT)

INSERT INTO kr_stock_asking_price (
  ticker, aspr_acpt_hour, askp1, askp2, askp3, askp4, askp5, askp6, askp7, askp8, askp9, askp10, bidp1, bidp2, 
  bidp3, bidp4, bidp5, bidp6, bidp7, bidp8, bidp9, bidp10, askp_rsqn1, askp_rsqn2, askp_rsqn3, 
  askp_rsqn4, askp_rsqn5, askp_rsqn6, askp_rsqn7, askp_rsqn8, askp_rsqn9, askp_rsqn10, bidp_rsqn1, 
  bidp_rsqn2, bidp_rsqn3, bidp_rsqn4, bidp_rsqn5, bidp_rsqn6, bidp_rsqn7, bidp_rsqn8, bidp_rsqn9, 
  bidp_rsqn10, askp_rsqn_icdc1, askp_rsqn_icdc2, askp_rsqn_icdc3, askp_rsqn_icdc4, askp_rsqn_icdc5, 
  askp_rsqn_icdc6, askp_rsqn_icdc7, askp_rsqn_icdc8, askp_rsqn_icdc9, askp_rsqn_icdc10, 
  bidp_rsqn_icdc1, bidp_rsqn_icdc2, bidp_rsqn_icdc3, bidp_rsqn_icdc4, bidp_rsqn_icdc5, 
  bidp_rsqn_icdc6, bidp_rsqn_icdc7, bidp_rsqn_icdc8, bidp_rsqn_icdc9, bidp_rsqn_icdc10, 
  total_askp_rsqn, total_bidp_rsqn, total_askp_rsqn_icdc, total_bidp_rsqn_icdc, 
  ovtm_total_askp_icdc, ovtm_total_bidp_icdc, ovtm_total_askp_rsqn, ovtm_total_bidp_rsqn, 
  ntby_aspr_rsqn, new_mkop_cls_code, antc_mkop_cls_code, stck_prpr, stck_oprc, stck_hgpr, stck_lwpr, 
  stck_sdpr, antc_cnpr, antc_cntg_vrss_sign, antc_cntg_vrss, antc_cntg_prdy_ctrt, antc_vol, 
  stck_shrn_iscd, vi_cls_code
) VALUES (
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 
  %s, %s, %s, %s, %s
)
ON CONFLICT (ticker) DO UPDATE SET
  aspr_acpt_hour = EXCLUDED.aspr_acpt_hour,
  askp1 = EXCLUDED.askp1,
  askp2 = EXCLUDED.askp2,
  askp3 = EXCLUDED.askp3,
  askp4 = EXCLUDED.askp4,
  askp5 = EXCLUDED.askp5,
  askp6 = EXCLUDED.askp6,
  askp7 = EXCLUDED.askp7,
  askp8 = EXCLUDED.askp8,
  askp9 = EXCLUDED.askp9,
  askp10 = EXCLUDED.askp10,
  bidp1 = EXCLUDED.bidp1,
  bidp2 = EXCLUDED.bidp2,
  bidp3 = EXCLUDED.bidp3,
  bidp4 = EXCLUDED.bidp4,
  bidp5 = EXCLUDED.bidp5,
  bidp6 = EXCLUDED.bidp6,
  bidp7 = EXCLUDED.bidp7,
  bidp8 = EXCLUDED.bidp8,
  bidp9 = EXCLUDED.bidp9,
  bidp10 = EXCLUDED.bidp10,
  askp_rsqn1 = EXCLUDED.askp_rsqn1,
  askp_rsqn2 = EXCLUDED.askp_rsqn2,
  askp_rsqn3 = EXCLUDED.askp_rsqn3,
  askp_rsqn4 = EXCLUDED.askp_rsqn4,
  askp_rsqn5 = EXCLUDED.askp_rsqn5,
  askp_rsqn6 = EXCLUDED.askp_rsqn6,
  askp_rsqn7 = EXCLUDED.askp_rsqn7,
  askp_rsqn8 = EXCLUDED.askp_rsqn8,
  askp_rsqn9 = EXCLUDED.askp_rsqn9,
  askp_rsqn10 = EXCLUDED.askp_rsqn10,
  bidp_rsqn1 = EXCLUDED.bidp_rsqn1,
  bidp_rsqn2 = EXCLUDED.bidp_rsqn2,
  bidp_rsqn3 = EXCLUDED.bidp_rsqn3,
  bidp_rsqn4 = EXCLUDED.bidp_rsqn4,
  bidp_rsqn5 = EXCLUDED.bidp_rsqn5,
  bidp_rsqn6 = EXCLUDED.bidp_rsqn6,
  bidp_rsqn7 = EXCLUDED.bidp_rsqn7,
  bidp_rsqn8 = EXCLUDED.bidp_rsqn8,
  bidp_rsqn9 = EXCLUDED.bidp_rsqn9,
  bidp_rsqn10 = EXCLUDED.bidp_rsqn10,
  askp_rsqn_icdc1 = EXCLUDED.askp_rsqn_icdc1,
  askp_rsqn_icdc2 = EXCLUDED.askp_rsqn_icdc2,
  askp_rsqn_icdc3 = EXCLUDED.askp_rsqn_icdc3,
  askp_rsqn_icdc4 = EXCLUDED.askp_rsqn_icdc4,
  askp_rsqn_icdc5 = EXCLUDED.askp_rsqn_icdc5,
  askp_rsqn_icdc6 = EXCLUDED.askp_rsqn_icdc6,
  askp_rsqn_icdc7 = EXCLUDED.askp_rsqn_icdc7,
  askp_rsqn_icdc8 = EXCLUDED.askp_rsqn_icdc8,
  askp_rsqn_icdc9 = EXCLUDED.askp_rsqn_icdc9,
  askp_rsqn_icdc10 = EXCLUDED.askp_rsqn_icdc10,
  bidp_rsqn_icdc1 = EXCLUDED.bidp_rsqn_icdc1,
  bidp_rsqn_icdc2 = EXCLUDED.bidp_rsqn_icdc2,
  bidp_rsqn_icdc3 = EXCLUDED.bidp_rsqn_icdc3,
  bidp_rsqn_icdc4 = EXCLUDED.bidp_rsqn_icdc4,
  bidp_rsqn_icdc5 = EXCLUDED.bidp_rsqn_icdc5,
  bidp_rsqn_icdc6 = EXCLUDED.bidp_rsqn_icdc6,
  bidp_rsqn_icdc7 = EXCLUDED.bidp_rsqn_icdc7,
  bidp_rsqn_icdc8 = EXCLUDED.bidp_rsqn_icdc8,
  bidp_rsqn_icdc9 = EXCLUDED.bidp_rsqn_icdc9,
  bidp_rsqn_icdc10 = EXCLUDED.bidp_rsqn_icdc10,
  total_askp_rsqn = EXCLUDED.total_askp_rsqn,
  total_bidp_rsqn = EXCLUDED.total_bidp_rsqn,
  total_askp_rsqn_icdc = EXCLUDED.total_askp_rsqn_icdc,
  total_bidp_rsqn_icdc = EXCLUDED.total_bidp_rsqn_icdc,
  ovtm_total_askp_icdc = EXCLUDED.ovtm_total_askp_icdc,
  ovtm_total_bidp_icdc = EXCLUDED.ovtm_total_bidp_icdc,
  ovtm_total_askp_rsqn = EXCLUDED.ovtm_total_askp_rsqn,
  ovtm_total_bidp_rsqn = EXCLUDED.ovtm_total_bidp_rsqn,
  ntby_aspr_rsqn = EXCLUDED.ntby_aspr_rsqn,
  new_mkop_cls_code = EXCLUDED.new_mkop_cls_code,
  antc_mkop_cls_code = EXCLUDED.antc_mkop_cls_code,
  stck_prpr = EXCLUDED.stck_prpr,
  stck_oprc = EXCLUDED.stck_oprc,
  stck_hgpr = EXCLUDED.stck_hgpr,
  stck_lwpr = EXCLUDED.stck_lwpr,
  stck_sdpr = EXCLUDED.stck_sdpr,
  antc_cnpr = EXCLUDED.antc_cnpr,
  antc_cntg_vrss_sign = EXCLUDED.antc_cntg_vrss_sign,
  antc_cntg_vrss = EXCLUDED.antc_cntg_vrss,
  antc_cntg_prdy_ctrt = EXCLUDED.antc_cntg_prdy_ctrt,
  antc_vol = EXCLUDED.antc_vol,
  stck_shrn_iscd = EXCLUDED.stck_shrn_iscd,
  vi_cls_code = EXCLUDED.vi_cls_code,
  updated_at = CURRENT_TIMESTAMP;