table_name: "kr_stock_price_detail"
primary_key: ["ticker"]

# 1단계: 자동화된 데이터 클리닝 규칙
auto_cleaning_rules:
  replace_as_null: ["0", 0] # 결측치로 처리할 값 목록
  drop_nulls_threshold_count: 100 # 이 개수 이상의 결측치를 가진 컬럼 제거
  drop_unique_threshold: 1 # 이 개수 이하의 고유값을 가진 컬럼 제거

# 2단계: 분석가가 직접 선정한 최종 사용 컬럼 목록
manual_column_selection:
  - ticker
  - new_hgpr_lwpr_cls_code
  - crdt_able_yn
  - stck_mxpr
  - elw_pblc_yn
  - prdy_clpr_vrss_oprc_rate
  - crdt_rate
  - marg_rate
  - lwpr_vrss_prpr
  - lwpr_vrss_prpr_sign
  - prdy_clpr_vrss_lwpr_rate
  - stck_lwpr
  - hgpr_vrss_prpr
  - hgpr_vrss_prpr_sign
  - prdy_clpr_vrss_hgpr_rate
  - stck_hgpr
  - oprc_vrss_prpr
  - oprc_vrss_prpr_sign
  - stck_llam
  - stck_sdpr
  - bstp_cls_code
  - stck_prdy_clpr
  - stck_prpr
  - prdy_vrss
  - prdy_vrss_sign
  - prdy_ctrt
  - acml_tr_pbmn
  - acml_vol
  - prdy_vrss_vol_rate
  - bstp_kor_isnm
  - stck_oprc
  - prdy_vol

# 3단계: 자동 데이터 타입 변환 규칙
auto_dtype_rules:
  category_ratio: 0.05
  date_success_rate: 0.95

# 4단계: 수동 데이터 타입 변환 맵
manual_dtype_map:
  category:
    - ticker
    - new_hgpr_lwpr_cls_code
    - lwpr_vrss_prpr_sign
    - hgpr_vrss_prpr_sign
    - oprc_vrss_prpr_sign
    - bstp_cls_code
    - prdy_vrss_sign
    - bstp_kor_isnm
  bool:
    - crdt_able_yn
    - elw_pblc_yn
  Int64:
    - stck_mxpr
    - lwpr_vrss_prpr
    - stck_lwpr
    - hgpr_vrss_prpr
    - stck_hgpr
    - oprc_vrss_prpr
    - stck_llam
    - stck_sdpr
    - stck_prdy_clpr
    - stck_prpr
    - prdy_vrss
    - acml_tr_pbmn
    - acml_vol
    - stck_oprc
    - prdy_vol
  float64:
    - prdy_clpr_vrss_oprc_rate
    - crdt_rate
    - marg_rate
    - prdy_clpr_vrss_lwpr_rate
    - prdy_clpr_vrss_hgpr_rate
    - prdy_ctrt
    - prdy_vrss_vol_rate
