table_name: "kr_stock_daily_itemchartprice"
primary_key: ["ticker", "stck_bsop_date"]

# 1단계: 자동화된 데이터 클리닝 규칙
auto_cleaning_rules:
  replace_as_null: ["0", 0] # 결측치로 처리할 값 목록
  drop_nulls_threshold_count: 425000 # 이 개수 이상의 결측치를 가진 컬럼 제거
  drop_unique_threshold: 1 # 이 개수 이하의 고유값을 가진 컬럼 제거

# 2단계: 분석가가 직접 선정한 최종 사용 컬럼 목록
manual_column_selection:
  - ticker
  - prdy_vrss
  - prdy_vrss_sign
  - acml_vol
  - acml_tr_pbmn
  - stck_oprc
  - stck_hgpr
  - stck_lwpr
  - stck_bsop_date
  - stck_clpr
  - flng_cls_code
  - prtt_rate

# 3단계: 자동 데이터 타입 변환 규칙
auto_dtype_rules:
  category_ratio: 0.05
  date_success_rate: 0.95

# 4단계: 수동 데이터 타입 변환 맵
manual_dtype_map:
  category:
    - ticker
    - prdy_vrss_sign
    - flng_cls_code
  int64:
    - prdy_vrss
    - acml_vol
    - acml_tr_pbmn
    - stck_oprc
    - stck_hgpr
    - stck_lwpr
    - stck_clpr
  float64:
    - prtt_rate
  datetime64[ns]:
    - stck_bsop_date
